# Generated by Django 6.0.7 on 2026-08-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='metadatos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='tipo',
            field=models.CharField(default='info', max_length=50),
        ),
    ]
